# Generated by Django 5.2.17 on 2026-10-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notice_version", models.CharField(max_length=32)),
                ("purposes", models.JSONField(default=list)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("granted", "Consent given"),
                            ("withdrawn", "Consent withdrawn"),
                        ],
                        default="granted",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("signup", "Given when the account was created"),
                            ("in_app", "Given from the account screen"),
                            (
                                "dpo",
                                "Recorded by the data protection office on the member's instruction",
                            ),
                        ],
                        default="in_app",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "notice_version", "action"),
                        name="one_consent_record_per_account_version_action",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("access", "Tell me what you hold about me (s.32, s.35)"),
                            (
                                "rectify",
                                "Correct data that is wrong or out of date (s.33(1)(a))",
                            ),
                            ("erase", "Delete my data (s.33(1)(b), s.44)"),
                            ("object", "Stop a processing I object to (s.39)"),
                            ("withdraw_consent", "Withdraw my consent (s.20(2))"),
                            ("stop_marketing", "Stop direct marketing (s.40)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("in_progress", "Being answered"),
                            ("answered", "Answered in full"),
                            ("partially_refused", "Answered, with part refused"),
                            ("refused", "Refused"),
                            ("withdrawn", "Withdrawn by the member"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_summary", models.TextField(blank=True, default="")),
                ("evidence", models.TextField(blank=True, default="")),
                (
                    "handled_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "due_at"],
                        name="compliance__status_0a95b1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["received", "in_progress"])),
                        fields=("account", "kind"),
                        name="one_open_request_per_kind",
                    )
                ],
            },
        ),
    ]
