# Generated by Django 5.2.17 on 2026-10-06 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasubjectrequest",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
