# Generated by Django 5.2.17 on 2026-10-06 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0002_alter_datasubjectrequest_requested_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctionsScreening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("un_consolidated", "UN Consolidated List"),
                            ("bog_sanctions", "Bank of Ghana Sanctions List"),
                            ("ofac_sdn", "OFAC Specially Designated Nationals"),
                            ("uk_hmt", "UK HM Treasury Consolidated List"),
                            ("eu_consolidated", "EU Consolidated List"),
                            ("world_check", "World-Check / Refinitiv"),
                            ("dow_jones", "Dow Jones Risk & Compliance"),
                            ("custom", "Custom List"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Screening Not Started"),
                            ("clear", "No Match Found"),
                            ("potential_match", "Potential Match — Review Required"),
                            ("confirmed_match", "Confirmed Match — Blocked"),
                            ("false_positive", "Cleared as False Positive"),
                            ("error", "Screening Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("name_screened", models.CharField(max_length=240)),
                (
                    "id_hash_screened",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "match_name",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("match_details", models.TextField(blank=True, default="")),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctions_screenings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="compliance__status_17cd18_idx",
                    ),
                    models.Index(
                        fields=["account", "status"],
                        name="compliance__account_db1517_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "clear"])),
                        fields=("account", "source"),
                        name="one_pending_or_clear_screening_per_account_source",
                    )
                ],
            },
        ),
    ]
