# Generated by Django 5.2.17 on 2026-10-06 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0003_sanctionsscreening"),
        ("susu", "0005_round_closing_float_pesewas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuspiciousTransactionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("structuring", "Possible Structuring (splitting amounts)"),
                            ("large_round", "Unusually Large Round Target"),
                            ("rapid_groups", "Rapid Group Creation"),
                            ("cross_border", "Cross-Border Funding Indicator"),
                            ("velocity", "High Contribution Velocity"),
                            ("round_anomaly", "Round Amount Anomaly"),
                            ("member_anomaly", "Member Behaviour Anomaly"),
                            ("sanctions_hit", "Sanctions Match on Transacting Party"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low — Review at Next Cycle"),
                            ("medium", "Medium — Review Within 24 Hours"),
                            ("high", "High — Review Immediately"),
                            ("critical", "Critical — Block and Escalate"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("rule_name", models.CharField(max_length=60)),
                ("rule_details", models.TextField()),
                ("detected_amount_pesewas", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open — Under Review"),
                            ("escalated", "Escalated to PSP Partner for STR Filing"),
                            ("filed", "STR Filed with FIC"),
                            ("closed_no_action", "Closed — No Action Required"),
                            ("closed_false_positive", "Closed — False Positive"),
                        ],
                        default="open",
                        max_length=25,
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                (
                    "str_reference",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("str_filed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "str_filed_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="str_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="str_alerts",
                        to="susu.contribution",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="str_alerts",
                        to="susu.susugroup",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="str_alerts",
                        to="susu.round",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity", "created_at"],
                        name="compliance__status_c294b4_idx",
                    ),
                    models.Index(
                        fields=["account", "status"],
                        name="compliance__account_b349da_idx",
                    ),
                    models.Index(
                        fields=["group", "created_at"],
                        name="compliance__group_i_203b4d_idx",
                    ),
                ],
            },
        ),
    ]
