# Generated by Django 5.2.17 on 2026-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", max_length=254, null=True, unique=True
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=120)),
                ("phone_verified", models.BooleanField(default=False)),
                ("id_verified", models.BooleanField(default=False)),
                (
                    "ghana_card_last4",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                (
                    "ghana_card_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "payout_destination",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "payout_destination_verified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("trust_score", models.PositiveSmallIntegerField(default=100)),
                ("flagged_total", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
