# Generated by Django 5.2.17 on 2026-10-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="anonymised_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="last_active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
