# Generated by Django 5.2.17 on 2026-10-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_anonymised_at_account_last_active_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="id_document_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="account",
            name="id_document_last4",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="account",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ghana_card", "Ghana Card"),
                    ("passport", "Passport"),
                    ("drivers_licence", "Driver's Licence"),
                    ("voter_id", "Voter ID Card"),
                    ("ssnit", "SSNIT Card"),
                    ("other", "Other Government ID"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="id_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="id_verified_by",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="account",
            name="sanctions_match",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="sanctions_match_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="account",
            name="sanctions_screened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="sanctions_screened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
