# Generated by Django 5.2.17 on 2026-10-03 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=8,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "mobile_money",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("missed_streak", models.PositiveSmallIntegerField(default=0)),
                ("debt_pesewas", models.BigIntegerField(default=0)),
                (
                    "debt_reason",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("debt_notified_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SusuGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("target_pesewas", models.BigIntegerField()),
                ("collection_day", models.PositiveSmallIntegerField(default=1)),
                ("cycle", models.PositiveIntegerField(default=1)),
                ("current_round", models.PositiveIntegerField(default=1)),
                ("turn_cursor", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("dormant", "Dormant"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "collection_account",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "collection_partner",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("invite_code", models.CharField(max_length=8, unique=True)),
                ("admin_trust_score", models.PositiveSmallIntegerField(default=100)),
                ("flagged_total", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administered_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("cycle", models.PositiveIntegerField(default=1)),
                ("target_pesewas", models.BigIntegerField()),
                ("fee_pesewas", models.BigIntegerField(default=0)),
                ("roster_snapshot", models.JSONField(default=list)),
                ("opened_at", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("short", "Short"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("carried_float_pesewas", models.BigIntegerField(default=0)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_rounds",
                        to="susu.membership",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="susu.susugroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="susu.susugroup",
            ),
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payout_key", models.CharField(max_length=80, unique=True)),
                ("amount_pesewas", models.BigIntegerField()),
                ("fee_pesewas", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="susu.membership",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="susu.round",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("round",), name="one_payout_per_round"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_pesewas__gt", 0)),
                        name="payout_amount_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_pesewas", models.BigIntegerField()),
                ("provider", models.CharField(max_length=24)),
                ("reference", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("flagged", "Flagged"),
                            ("disputed", "Disputed"),
                            ("void", "Void"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "manual_verification_reason",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("idempotency_key", models.UUIDField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="susu.membership",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="susu.round",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["round", "status"],
                        name="susu_contri_round_i_cfba18_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "verified")),
                        fields=("round", "membership"),
                        name="one_verified_contribution_per_member_per_round",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_pesewas__gte", 100)),
                        name="contribution_at_least_one_cedi",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="susugroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_pesewas__gt", 0)),
                name="group_target_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="susugroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("collection_day__gte", 0), ("collection_day__lte", 6)
                ),
                name="group_collection_day_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="round",
            index=models.Index(
                fields=["group", "outcome"], name="susu_round_group_i_92f1c4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outcome", "open")),
                fields=("group",),
                name="one_open_round_per_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("group", "number"), name="one_round_per_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_pesewas__gt", 0)),
                name="round_target_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("group", "account"), name="one_membership_per_group_per_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("group", "order"), name="one_membership_per_rotation_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(("debt_pesewas__gte", 0)),
                name="membership_debt_not_negative",
            ),
        ),
    ]
