# Generated by Django 5.2.17 on 2026-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("susu", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contribution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="one_contribution_per_idempotency_key",
            ),
        ),
    ]
