# Generated by Django 5.2.17 on 2026-10-04 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("susu", "0002_contribution_one_contribution_per_idempotency_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("collection", "Collection"),
                            ("payout", "Payout"),
                            ("fee", "Fee"),
                            ("reversal", "Reversal"),
                            ("debt", "Debt"),
                            ("float_adjustment", "Float Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_postings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_postings",
                        to="susu.susugroup",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_postings",
                        to="susu.round",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("collection", "Collection"),
                            ("payout", "Payout"),
                            ("fee", "Fee"),
                            ("reversal", "Reversal"),
                            ("debt", "Debt"),
                            ("float_adjustment", "Float Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        choices=[
                            ("partner_account", "Partner collection account"),
                            ("group_pot", "Group pot owed to members"),
                            ("fee_expense", "Transfer fee expense"),
                            ("fee_payable", "Transfer fee payable to the provider"),
                            ("debt_receivable", "Agreed debt owed to the group"),
                            ("member_payable", "Member owed money"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=6
                    ),
                ),
                ("amount_pesewas", models.BigIntegerField()),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="susu.susugroup",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="susu.round",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="susu.ledgerposting",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role", models.CharField(default="system", max_length=16)),
                ("action", models.CharField(max_length=60)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("round_number", models.IntegerField(blank=True, null=True)),
                ("from_state", models.CharField(blank=True, default="", max_length=20)),
                ("to_state", models.CharField(blank=True, default="", max_length=20)),
                ("reason", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="susu.susugroup",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["group", "action"],
                        name="susu_audite_group_i_e49d1e_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ledgerposting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference__gt", "")),
                fields=("round", "entry_type", "reference"),
                name="one_ledger_posting_per_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["group", "account"], name="susu_ledger_group_i_0c685f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_pesewas__gt", 0)),
                name="ledger_amount_positive",
            ),
        ),
    ]
