# Generated by Django 5.2.17 on 2026-10-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("susu", "0003_ledgerposting_ledgerentry_auditevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="debt_revision",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
