# Generated by Django 5.2.17 on 2026-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("susu", "0004_round_debt_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="closing_float_pesewas",
            field=models.BigIntegerField(default=0),
        ),
    ]
