# Generated by Django 5.2.17 on 2026-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("susu", "0005_round_closing_float_pesewas"),
    ]

    operations = [
        migrations.AddField(
            model_name="susugroup",
            name="fee_pesewas",
            field=models.BigIntegerField(default=0),
        ),
    ]
