# Generated by Django 5.2.17 on 2026-10-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("susu", "0006_add_group_fee_pesewas"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_pesewas", models.BigIntegerField()),
                ("settled_pesewas", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims_against",
                        to="susu.membership",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims_owed",
                        to="susu.membership",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="susu.round",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_pesewas__gt", 0)),
                        name="debtclaim_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("settled_pesewas__gte", 0)),
                        name="debtclaim_settled_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("settled_pesewas__lte", models.F("amount_pesewas"))
                        ),
                        name="debtclaim_settled_not_exceeding_amount",
                    ),
                ],
            },
        ),
    ]
